### PR TITLE
Adding ml5.setBackend()

### PR DESCRIPTION
**Pull request by shiffman**
@ziyuan-linn, what are your thoughts on the best way to add this method?

### CODE REVIEW

**Comment by ziyuan-linn** [comment]
@shiffman Ah, I did not know this branch existed. My implementation is here: https://github.com/ml5js/ml5-next-gen/tree/ml5-set-backend. Sorry about putting things in two places.

I put `setBackend()` in one of the util files and added a custom error since the tf.js is not very intuitive. I think we also have to somehow make it clear this method will only work for tf.js-based models. Documenting it on the website might be a good idea.

**Comment by shiffman** [comment]
@ziyuan-linn did you push your commits to that branch? I just merged them here but don't see them now! It's probably best for you to open a new pull request and I'll just close this one!

**Comment by ziyuan-linn** [comment]
@shiffman Ah yeah I forgot to push my commits. I will open a new pull request!

**Comment by shiffman** [comment]
Great! (Closing and moving to #37)

**Pull request closed without merging**
