### PR TITLE
Update tensorflow.js version

### LINKED ISSUE #231: Getting error message in console: Initialization of backend webgpu failed
### Issue Type

Runtime Error, Unexpected Behavior

### ml5.js Version

v.1.2.0 Latest

### Development Environment

p5js editror

### Browser & Operating System

Chrome Macos Version 131.0.6778.69 (Official Build) (arm64)

### Issue Description

From documentation:
https://docs.ml5js.org/#/reference/bodypose

run the example sketch:
https://editor.p5js.org/ml5/sketches/hMN9GdrO3
Following error is displayed in console:
Initialization of backend webgpu failed
index.js:259 TypeError: t.requestAdapterInfo is not a function
    at Object.factory (pose-detection.esm.js:17:97544)
    at async b.ready (engine.js:93:13)
    at async fG.loadModel (index.js:256:7)

### Minimal Reproducible Example

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by shiffman**
I hope this resolves #231?

### CODE REVIEW

**Comment by shiffman** [comment]
@ziyuan-linn unfortunately I am still getting the error although maybe I missed a step rebuilding the library, let me know if you have a chance to take a look!

**Comment by ziyuan-linn** [comment]
@shiffman Looks like there was an entry `"@tensorflow/tfjs-backend-webgpu": "^4.17.0"` in `devDependencies`. I moved it to `dependencies` and upgraded it to `4.22`. However, this did not stop the warning.

I then deleted `yarn.lock` and ran `yarn` to regenerate the lock file from scratch, and the warning is gone. I am not sure why this fix works though. 

Could you please help me verify that the warning is gone on your end as well?

**Comment by shiffman** [comment]
Yes, I can confirm the error is gone and also `webgpu` is working as the backend! I'm going to go ahead and merge this, shall I do a quick patch release?

**Comment by ziyuan-linn** [comment]
Great! Yes, I think we can do a patch release!

**Pull request merged**
