### PR TITLE
Create `/tests` folder, remove `canvas` polyfill

### LINKED ISSUE #97: Error installing dependencies
I am trying to run the `yarn` command to install the dependencies but got this error.

```
error /Users/ziyuanlin/Documents/VS Code/ml5-next-gen/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --update-binary
Arguments: 
Directory: /Users/ziyuanlin/Documents/VS Code/ml5-next-gen/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@18.15.0 | darwin | arm64
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@18.15.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.15.0 | darwin | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.15.0 | darwin | arm64
gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/ziyuanlin/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ziyuanlin/Documents/VS Code/ml5-next-gen/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ziyuanlin/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ziyuanlin/Library/Caches/node-gyp/18.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/ziyuanlin/Library/Caches/node-gyp/18.15.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/ziyuanlin/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/ziyuanlin/Library/Caches/node-gyp/18.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/ziyuanlin/Documents/VS Code/ml5-next-gen/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/ziyuanlin/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 23.3.0
gyp ERR! command "/Users/ziyuanlin/.nvm/versions/node/v18.15.0/bin/node" "/Users/ziyuanlin/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/Users/ziyuanlin/Documents/VS Code/ml5-next-gen/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/ziyuanlin/Documents/VS Code/ml5-next-gen/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
gyp ERR! cwd /Users/ziyuanlin/Documents/VS Code/ml5-next-gen/node_modules/canvas
gyp ERR! node -v v18.15.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/ziyuanlin/.nvm/versions/node/v18.15.0/bin/node /Users/ziyuanlin/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/ziyuanlin/Documents/VS Code/ml5-next-gen/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/ziyuanlin/Documents/VS Code/ml5-next-gen/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/ziyuanlin/Documents/VS Code/ml5-next-gen/node_modules/canvas/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Darwin 23.3.0
node-pre-gyp ERR! command "/Users/ziyuanlin/.nvm/versions/node/v18.15.0/bin/node" "/Users/ziyuanlin/Documents/VS Code/ml5-next-gen/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
node-pre-gyp ERR! cwd /Users/ziyuanlin/Documents/VS Code/ml5-next-gen/node_modules/canvas
node-pre-gyp ERR! node -v v18.15.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok 
Failed to execute '/Users/ziyuanlin/.nvm/versions/node/v18.15.0/bin/node /Users/ziyuanlin/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/ziyuanlin/Documents/VS Code/ml5-next-gen/node_modules/canvas/build/Rel
```

It only appears on my M1 MacBook with macOS 14.3 and not on my Windows machine. The error disappeared when I reverted the changes of #82.

### PR DESCRIPTION
**Pull request by lindapaiste**
Fixes #97 
Implements @gohai's recommendations in https://github.com/ml5js/ml5-next-gen/pull/82#issuecomment-2010919727

Changes: 
- Move all test-related code to a new folder `/tests`.
  - Move the `/coverage` folder.
  - Move the jest configuration file (`jest.config.js`).
    - Specify the location in `package.json` since it is no longer at the root.
    - Adjust the paths in the config using `<rootDir>` syntax.
  - Use jest only on the `/unit` folder.
  - Add an `/integration` folder for tests requiring a browser.  These are not run at the moment and will need to be set up in a future PR.
- Uninstall `canvas` package - fixes #97 
  - Remove the polyfill from the `setupTests.js` file. 
  - Move files which involve reading an image into the `/integration` folder.
- Delete Babel config files and put the config in `package.json`.

### CODE REVIEW

**Comment by shiffman** [comment]
This looks great, excited to merge! @gohai would have time to review as a second pair of eyes?

**Comment by shiffman** [comment]
@ziyuan-linn and I are reviewing this together and the tests run on my machine but not his... I'm going to merge this but we will continue to investigate. 

I'll note that I had to run `npm rebuild @tensorflow/tfjs-node --build-addon-from-source` for the tests to work.

**Comment by gohai** [comment]
I am getting an error doing `yarn install` (not sure if this the same issue @ziyuan-linn had?):

```
error .../ml5-ng/node_modules/@tensorflow/tfjs-node: Command failed.
```

From the detailed error message, I am getting the sense that it _might_ be related to me not having Xcode installed? ([see also](https://github.com/tensorflow/tfjs/blob/master/tfjs-node/README.md#mac-os-x-requires-xcode)) (I do have the command-line build tools, though)

```
  File "/Users/gohai/.nvm/versions/node/v18.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1737, in _GetXcodeEnv
    "XCODE_VERSION_ACTUAL": XcodeVersion()[0],
                            ^^^^^^^^^^^^^^
  File "/Users/gohai/.nvm/versions/node/v18.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1507, in XcodeVersion
    version = CLTVersion()  # macOS Catalina returns 11.0.0.0.1.1567737322
              ^^^^^^^^^^^^
  File "/Users/gohai/.nvm/versions/node/v18.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1545, in CLTVersion
    return re.search(regex, output).groupdict()["version"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

@lindapaiste Since probably a lot of people will run into this issue: what's your thought of moving `@tensorflow/tfjs-node`  into `optionalDependencies`? When I do this, I am still seeing that installing `tfjs-node` failed (the first time running `yarn install`):

```
warning Error running install script for optional dependency: ".../ml5-ng/node_modules/@tensorflow/tfjs-node: Command failed.
```

.. but the installation process continues with:

```
$ patch-package
patch-package 8.0.0
Applying patches...
@tensorflow-models/face-landmarks-detection@1.0.5 ✔
✨  Done in 46.85s.
```

**Comment by shiffman** [comment]
@gohai just curious does running this command fix the error?

```sh
npm rebuild @tensorflow/tfjs-node --build-addon-from-source
```

**Comment by ziyuan-linn** [comment]
@gohai I'm not sure if this is the same issue, but removing any spaces in the directory names containing the project fixed the issue for me.

**Comment by gohai** [comment]
I filed an issue with tfjs [here](https://github.com/tensorflow/tfjs/issues/8228). I got the same error when I ran `npm rebuild @tensorflow/tfjs-node --build-addon-from-source`, and the path also doesn't have any spaces. So temperamental!

In the Readme there is a mention that [Python 2.7 is needed](https://github.com/tensorflow/tfjs/tree/master/tfjs-node#windows--mac-os-x-requires-python-27) - hoping it's not that, which would make it very difficult for people to get going..

**Comment by lindapaiste** [comment]
We could consider removing `@tensorflow/tfjs-node` from the dev dependencies and running the tests using the main/browser version.  We will get warnings in the console about how we should be using the Node version, but I get a lot of those still even when I try to use the Node version.

@gohai I definitely appreciate you calling out the difficult dependencies.  This is another situation where I've previously installed that package on my computer so it installs easily *for me* and I forget that there was some complicated setup required at some point in the past.

**Pull request merged**
