### PR TITLE
Image Classifier update

### PR DESCRIPTION
**Pull request by OrpheasK**
This PR fixes the issue #166 that @jackbdu brought into attention and also offers a chance to decide upon for the use/name of the `topk` parameter in conjunction with `kNumber` as already mentioned in issue [#83](https://github.com/ml5js/ml5-next-gen/issues/83) by @lindapaiste. 

Also recently mentioned in #83 is the support of local loading of TM models among other subjects, which can be incorporated in this or another PR depending on the priority each aspect will be given.

### CODE REVIEW

**Review by ziyuan-linn — APPROVED** [review]
This looks good to me! I don't really have a strong opinion on the naming of `topk`, but perhaps another option could be `classes`. `classes: 4` returns the top 4 classifications. 

Personally I think we should only use the `ml5.imageClassifier({topk: 4})` and not `myImageClassifier.classify(image, 4)`, so the interface is more consistent with the other models. This might be a breaking change though, and I don't feel strongly about this either.

**Comment by lindapaiste** [comment]
`resultCount` might also make sense.

**Comment by shiffman** [comment]
> Personally I think we should only use the ml5.imageClassifier({topk: 4}) and not myImageClassifier.classify(image, 4), so the interface is more consistent with the other models. This might be a breaking change though, and I don't feel strongly about this either.

@ziyuan-linn can you elaborate on this? What other models follow this pattern? Perhaps it's better to conform the other models to how we are doing it here? I think having the # of classes returned specified with `classify()` is more intuitive?

**Comment by ziyuan-linn** [comment]
@shiffman The other pretrained models like `BodySegmentation` and `FaceMesh` only accept a media element and an optional callback on the detection methods and do not accept any kind of options. For example `faceMesh.detect(image, gotFaces);`. All the options are set during the `ml5.faceMesh()` call. 

I think setting the number of classes returned is unique to `ImageClassifier` (and maybe soundclassifier?).

I agree that the number of classes on the `classify` method is more intuitive.

**Comment by shiffman** [comment]
Apologies for letting this PR languish for a bit! Based on the discussion we had at our previous Thursday meeting, we decided to allow for passing in the number of desired classes + confidence scores to be returned as an argument to the `classify()` function itself. We can then extend this pattern to other models that work in a similar way (right now it would only be `ml5.neuralNetwork()` for the `"classification"` task.  I'll open an issue regarding incorporating this in examples and website documentation.

**Pull request merged**
