### PR TITLE
BodyPose cleanup

### PR DESCRIPTION
**Pull request by ziyuan-linn**
This PR updates the comments and refactors the code of BodyPose. No change to the user API.
- update incorrect license info: MIT License -> ml5.js License.
- add file description and helpful links at the beginning of the file.
- format and clean up options object JSDoc comment.
- move mold objects/schemas for `handleOptions` next to the options object comments.
- add comment description to each property of `BodyPose` class.
- update various comments for clarity
- refactor some variable names for clarity

This PR also removes the `window._incrementPreload` and `window._decrementPreload` calls to address the bug in #175.

### CODE REVIEW

**Review by shiffman — COMMENTED** [review]
This looks great, thank you @ziyuan-linn! Looks like you tagged @alanvww for a review, I'm happy to merge afterwards!

**Review by alanvww — APPROVED** [review]

**Comment by alanvww** [comment]
Awesome work! Thanks for letting me know about the update, I will work on the doc ASAP.

@shiffman We are ready to merge!

**Comment by lindapaiste** [comment]
Thoughts:

It might make sense to move functions like mirrorBoundingBox to a utility file, if we want to use that logic in multiple models.

There are some types that can be more specific, but it’s annoying if we have to write out the union of possible image types every time.  The return types could also be more specific (an array of what?).  We can define a type for the prediction object and instead of Promise<Array> it can be Promise<Array<BodyPrediction>>.  That might not be worth the effort, unless…

It would be really great if we can figure out a way to sync property descriptions between the code comments and the documentation.

**Comment by shiffman** [comment]
Thank you for the feedback @lindapaiste, feel free to open any issues with proposals for these changes if you like!

**Pull request merged**
